title: SoraArticle
author:
  name: Grav
  email: 'joe@test.com'
  description: "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."
  url: http://getgrav.org/
  logo: logo.jpg
blog:
  route: ''
metadata:
    description: 'Sora Article is a minimal Theme designed for blogger, converted to Grav.'
taxonomies: [category,tag,month]
google_translate_token: "a4a3caaf1d41a924-5fa21ae3833dd6c1-g99933840045dca1c-26"

mainmenu:
    - text: Layout
      url: "#" 
    - text: Shortcodes
      url: "#" 
    - text: Pages
      url: "#" 
    - text: Contact
      url: "#"  

# MasterSlider Options
masterslider:
    - image: 1.jpg
    - image: 2.jpg
    - image: 3.jpg

masterslider_setup:
    width           : 1140
    height          : 500
    space           : 0
    start           : 1
    grabCursor      : "false"
    swipe           : "true"
    mouse           : "false"
    layout          : "fullwidth"
    wheel           : "false"
    autoplay        : "true"
    instantStartLayers: "false"
    loop            : "true"
    shuffle         : "false"
    preload         : 2
    heightLimit     : "true"
    autoHeight      : "false"
    smoothHeight    : "true"
    endPause        : "false"
    overPause       : "true"
    fillMode        : "fill"
    centerControls  : "false"
    layersMode      : "center"
    hideLayers      : "false"
    fullscreenMargin: 0
    speed           : 20
    dir             : "h"
    parallaxMode    : 'swipe'
    view            : "basic"


# Footer
# Feedburner
feedburner:
  title: Follow by Email
  id: SoraArticle
  text: "Subscribe here to get our newsletter, it is safe just Put your Email and Press Enter"

# Labels
labels:
  title: Labels
  items:
    - url: #
      label: Cricket
    - url: #
      label: Fashion
    - url: #
      label: Fun
    - url: #
      label: India
    - url: #
      label: Punjab
    - url: #
      label: Sport
    - url: #
      label: Tech
    - url: #
      label: World    

# Footer module 
footer:
  title: Lipsum
  content: "Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Idque Caesaris facere voluntate liceret: sese habere. Magna pars studiorum, prodita quaerimus.<br /><br />Nihilne te nocturnum praesidium Palati, nihil urbis vigiliae. Non equidem invideo, miror magis posuere velit aliquet."
  
# Copyright
copyright:
    text1: Copyright 
    year: 2015
    url: http://sora-article-soratemplates.blogspot.in/
    text2: Sora Article

copyright2:
    text1: ", Ported by" 
    url: http://getgrav.org/
    text2: Grav Team



